### ISSUE TITLE
priest crit chance and other minor bugs

### ISSUE THREAD

**Issue by ownlyme** [getov/CharacterStatsClassic#45]
1.
according to warcraftlogs, this formula should better describe my critchance:
https://wowwiki.fandom.com/wiki/Spell_critical_strike
1.24 + Int/59.2 + BonusCrit

2.
it doesn't count the 2% holy crit chance of benediction

3.
it doesn't count the +4 mp5 from the zg head and legs enchant (+heal of it is getting picked up correctly)

**Comment by getov** [comment]
1. I don't see an explanation of this formula for level 60 in the link ?
2. It should be adding it already. Use https://classic.wowhead.com/gear-planner to put in your gear and send me both an in-game screenshot and link to your gear setup. I can't test this because I don't have a priest, but maybe I can figure something out from the screenshots
3. I will add them in the next release

**Comment by ownlyme** [comment]
1. 
take a look at the table under "base spell crit", it tells you the "class specific constant" and the amount of intellect per crit.
you just need to put in these values into the formula (section "formula"^^)
2.
no idea what you need my gear planner for but here you go:
https://classic.wowhead.com/gear-planner/priest/human/AjwAAUIZAk2tA0IcBUIbBkIdB0IaCEvtCUIeClPWC1R0DELWDUtYDkglD0vmEEiwEkvr

screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/6101261/92921772-fab71280-f434-11ea-83de-5f9dfd392c17.png)
as you can see, my holy crit is only 5% higher than my other crits, but i have 5% from talents and 2% from benediction.

raidbuffed i have 463 intelligence so according to my formula i should have 16.06% crit.
this is my guild at warcraftlogs, take a look at a few runs - my crit chance should be at least 16% on average.
https://classic.warcraftlogs.com/guild/eu/lakeshire/schlachthaus

**Comment by getov** [comment]
I started asking people to upload their gear + screenshots because I've had FALSE bug reports many times. I don't want to waste my time only to find out there was no bug.

In your case it's really strange because I cannot find out what's wrong. I have an explicit check for Benediction and it seems to be executing it.

Yes, I am sure my addon is picking spell crit from items. There are some exceptions like Benediction which need additional handling.

**Comment by ownlyme** [comment]
strange, nowhere in your files i was able to find the words "benediction" or "18608" ...
i have version 3.5.4

**Comment by getov** [comment]
The newest version is 3.6.3. Maybe that's why

**Comment by ownlyme** [comment]
i'm really sorry, just updated to 3.6.2 and benediction works

**Comment by getov** [comment]
The ZG enchant should work now in 3.6.3
